import type { Config } from "tailwindcss";
import animate from "tailwindcss-animate";

const config: Config = {
  darkMode: ["class"],
  content: ["./src/components/**/*.{js,ts,jsx,tsx,mdx}", "./src/app/**/*.{js,ts,jsx,tsx,mdx}"],
  theme: {
    extend: {
      colors: {
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "var(--primary)",
          light: "var(--primary-light)",
          dark: "var(--primary-dark)",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "var(--secondary)",
          light: "var(--secondary-light)",
          dark: "var(--secondary-dark)",
          foreground: "hsl(var(--secondary-foreground))",
        },
        neutral: {
          "100": "var(--neutral-100)",
          "200": "var(--neutral-200)",
          "300": "var(--neutral-300)",
          "400": "var(--neutral-400)",
          "500": "var(--neutral-500)",
          "600": "var(--neutral-600)",
          "700": "var(--neutral-700)",
          "800": "var(--neutral-800)",
          "900": "var(--neutral-900)",
          DEFAULT: "var(--neutral-500)",
        },
        card: { DEFAULT: "hsl(var(--card))", foreground: "hsl(var(--card-foreground))" },
        popover: { DEFAULT: "hsl(var(--popover))", foreground: "hsl(var(--popover-foreground))" },
        muted: { DEFAULT: "hsl(var(--muted))", foreground: "hsl(var(--muted-foreground))" },
        accent: { DEFAULT: "hsl(var(--accent))", foreground: "hsl(var(--accent-foreground))" },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
      },
      spacing: { "128": "32rem", containerPX: "1.5rem" },
      boxShadow: { custom: "0px 4px 15px rgba(0, 0, 0, 0.1)" },
      fontFamily: {
        // Loaded by next/font in app/layout.tsx; it used to name a font that was never loaded.
        lato: ["var(--font-lato)", "Arial", "Helvetica", "sans-serif"],
      },
      fontSize: {
        d1: "48px",
        d2: "40px",
        d3: "36px",
        "d-d1": "64px",
        "d-d2": "56px",
        "d-d3": "48px",
        h1: "40px",
        h2: "36px",
        h3: "24px",
        h4: "20px",
        "d-h1": "48px",
        "d-h2": "42px",
        "d-h3": "36px",
        "d-h4": "40px",
        xs: "10px",
        sm: "12px",
        base: "14px",
        lg: "16px",
        xl: "18px",
        "2xl": "22px",
        "3xl": "30px",
        "4xl": "36px",
        "5xl": "48px",
        "6xl": "64px",
        "d-xs": "12px",
        "d-sm": "14px",
        "d-base": "16px",
        "d-lg": "18px",
        "d-xl": "20px",
        "d-2xl": "24px",
        "d-3xl": "36px",
        "d-4xl": "40px",
        "d-5xl": "64px",
        "d-6xl": "80px",
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        slideIn: {
          "0%": { transform: "translateY(-100%)", opacity: "0" },
          "100%": { transform: "translateY(0)", opacity: "1" },
        },
      },
      animation: { slideIn: "slideIn 0.5s ease-out" },
    },
  },
  plugins: [animate],
};

export default config;
